= Cahier des Charges
:library: Asciidoctor
:idprefix:
:numbered:
:imagedir:
:toc: manual
:toclevels:
:css-signature: demo
:toc-placement: preamble
//:max-width: 800px
//:doctype: book
//:sectids!:


ifdef::env-github[]
++++
<a name="objectif"></a>
++++
endif::env-github[]

[[objectif]]
.Objectif
****
TIP: Ce document concerne uniquement la V0
****

== Presentation du sujet 

Pour s’adapter aux exigenses d’instantanéité de les banques françaises ont accentué leurs efforts de restructuration et leurs investissements dans le digital.

La banque DailyBank souhaite développer une application JAVA-Oracle de gestion des comptes clients pour remplacer plusieurs outils obsolètes. Ce développement s’inscrit dans le cadre de la restructuration de ses services bancaires et l’application sera déployée dans les 100 agences que compte son réseau. Vous travaillerez à partir d’une application existante « Daily Bank » qu’il faudra adapter aux nouveaux besoins de la banque.

== Analyse de l'existant
.Dans la version deja existante (V0)

. Un guichetier peut:
.. Modifier les information client
.. Créer un nouveau client
.. Consulter un compte
.. Débiter un compte
. Un chef d'agence peut:
.. Rendre inactif un client

== Analyse des besoins
.Version 1
Les besoins de la banque pour cette  v1 de l'application dépendent des différents utilisateurs :

* Guichetier :
** Créditer/débiter un compte (java et BD avec procédure stockée)
** Créer un compte
** Effectuer un virement de compte à compte
** cloturer un compte
* Chef d'agence :
** Gérer (faire le « CRUD ») les employés (guichetier et chef d’agence)

== Analyse des contraintes
===== Contraintes techniques

* Depot sous GIT
* Rédaction du CDCU en asciidoc
* Rdaction des documentation technique et utilisateur
* Livraison d'un .jar, code source, javadoc

===== Contraintes organisationnelles

